apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-configmap
  namespace: default
data:
  reverse_proxy.yaml: |
    proxy:
      listen:
        address: 0.0.0.0
        port: 8080
      services:
      - name: my-service
        domain: my-service.my-company.com
        hosts:
        - address: 10.97.135.24
          port: 9090
        - address: 10.108.74.161
          port: 9091      
      # Supported load balancing algorithms
      #  round-robin
      #  random
      load_balancing:
        algorithm: round-robin

